server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: springai-web
  
  # 数据源配置 (H2内存数据库)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  # H2控制台 (开发环境)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Spring AI 配置
  ai:
    # 使用官方Spring AI DeepSeek配置
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      chat:
        enabled: true
        options:
          model: ${DEEPSEEK_MODEL:deepseek-chat}
          temperature: 0.7
          max-tokens: 4000
          frequency-penalty: 0.0
          presence-penalty: 0.0
          top-p: 1.0
    
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000
      # 禁用OpenAI embedding以避免冲突
      embedding:
        enabled: false
    
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: llama2
          temperature: 0.7
      # 禁用Ollama embedding以避免冲突
      embedding:
        enabled: false
    
    # 禁用向量存储自动配置
    vectorstore:
      pgvector:
        enabled: false

# 日志配置
logging:
  level:
    com.compass.springai: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.compass.springai.web.controller 